### ISSUE TITLE
too hard to install external deps

### ISSUE THREAD

**Issue by dominictarr** [ssbc/patchwork-builder#4]
I couldn't get this running on archlinux, electron-builder uses too many weird commands that needs to be installed and then xorriso wants wants libreadline.so.6 but I have libreadline.so.7 ... I just know that changing that is gonna break everything... is there any other way to do with with less external dependencies?

**Comment by mmckegg** [comment]
Are you still having problems with this?

I've now been using this for over a year, and works great! I can even build for all platforms with this.

Closing for now.
