### ISSUE TITLE
Code usage

### ISSUE THREAD

**Issue by gmarcos87** [ssbc/patchwork-builder#8]
Hi, I'd like to borrow this code for another project. How to give you credit?

**Comment by christianbundy** [comment]
Hey! This was released under the [ISC](https://github.com/ssbc/patchwork-builder/blob/1a6a04493d3709d0c4633daccdf2167f7c8dfb52/package.json#L73) license, so you can copy/redistribute as long as you follow:

> Permission to use, copy, modify, and/or distribute this software for any purpose with or without fee is hereby granted, provided that the above copyright notice and this permission notice appear in all copies.
>
> THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

Please let me know if you have any other questions!
